FROM ubuntu:20.04

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && \
apt-get install -y python3 python3-pip jq openssh-server iproute2 vim curl unzip tzdata git ca-certificates curl gnupg lsb-release

# Docker install
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
apt-get update && \
apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose

# container configuration
RUN ln -fs /usr/share/zoneinfo/TZ_CONFIG /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata && \
    mkdir -p -m0755 /var/run/sshd

# Install pip packages
RUN pip install awscli

RUN useradd --uid SYS_UID sysadmin && \
    echo "SYS_USER:SYS_GROUP" | chpasswd && \
    mkdir /home/SYS_USER/.ssh -p && \
    chmod 700 /home/SYS_USER/.ssh && \
    mkdir -p -m0755 /var/run/sshd

# Copy ssh public key
COPY SYS_USER.pub /home/SYS_USER/.ssh/authorized_keys

RUN chown SYS_USER -R /home/SYS_USER && \
    chmod 400 /home/SYS_USER/.ssh/authorized_keys


CMD /usr/sbin/sshd -D

# docker build -t ervws:v1 .